In [2]:
import torch

In [3]:
a = torch.tensor([1,2,3,4])
a

tensor([1, 2, 3, 4])

In [6]:
a0 = torch.arange(24).reshape(-1, 2, 4)
a1 = torch.arange(24).reshape(-1, 4, 2)
torch.bmm(a0, a1)

tensor([[[  28,   34],
         [  76,   98]],

        [[ 428,  466],
         [ 604,  658]],

        [[1340, 1410],
         [1644, 1730]]])

In [7]:
a0 = torch.tensor([1,2,3])
a0.dtype

torch.int64

In [8]:
a0.type()

'torch.LongTensor'

In [9]:
a0 = torch.tensor([1,2,3])
a0.type()

'torch.LongTensor'

In [14]:
a0 = torch.tensor([1,2,3])
a0.dtype

torch.int64

In [15]:
a = torch.tensor([1.], requires_grad=True)
a.dtype

torch.float32

In [16]:
a = torch.zeros(6).reshape(2,3)
b = torch.ones(6).reshape(2,3)
torch.cat([a,b])

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [18]:
torch.cat([a,b], dim=1)

tensor([[0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.]])

In [19]:
a = torch.zeros(6).reshape(2, 3)
b = torch.ones(6).reshape(2, 3)
c = b + 1
torch.stack([a, b, c])

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[2., 2., 2.],
         [2., 2., 2.]]])

In [20]:
a = torch.arange(6).reshape(2, 3)
a

tensor([[0, 1, 2],
        [3, 4, 5]])

In [21]:
a.unsqueeze(0)

tensor([[[0, 1, 2],
         [3, 4, 5]]])

In [25]:
a = torch.arange(6).reshape(2,3)
a

tensor([[0, 1, 2],
        [3, 4, 5]])

In [27]:
a.unsqueeze(0)

tensor([[[0, 1, 2],
         [3, 4, 5]]])

In [28]:
a = torch.arange(12).reshape(2, 2, -1)
a

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])

In [29]:
a.permute(2, 0, 1)

tensor([[[ 0,  3],
         [ 6,  9]],

        [[ 1,  4],
         [ 7, 10]],

        [[ 2,  5],
         [ 8, 11]]])

In [30]:
x1 = torch.tensor([1.], requires_grad=True)
x2 = torch.tensor([2.], requires_grad=True)
x3 = torch.tensor([3.], requires_grad=True)

In [31]:
z = (x1 - 2 * x2 -1)**2 + (x2 * x3 - 1)**2 + 1

In [32]:
z.backward()
x1.grad

tensor([-8.])

In [33]:
x2.grad

tensor([46.])

In [34]:
x3.grad

tensor([20.])